#!/bin/sh

ROOTDIR=$1
RELDIR=$2
DataFile=$3

shift
shift
shift

ERTS_VSN=`awk '{print $1}' $DataFile`
VSN=`awk '{print $2}' $DataFile`

BINDIR=`pwd`"/erts-$ERTS_VSN/bin"
PATH=$PATH:$BINDIR
EMU=beam
PROGNAME=`echo $0 | sed 's/.*\///'`

export PATH
export EMU
export ROOTDIR
export BINDIR
export PROGNAME
export RELDIR

. ./bin/startup.conf
exec $BINDIR/erlexec -boot $RELDIR/$VSN/start -config $RELDIR/$VSN/sys -heart -env HEART_BEAT_TIMEOUT 30 ${1+"$@"}
