%%% This file was automatically generated by snmpc_mib_to_hrl version 4.12
%%% Date: 18-Jan-2009::11:31:29
-ifndef('EX1-MIB').
-define('EX1-MIB', true).

%% Oids

-define(example1, [1,3,6,1,3,7]).
-define(myName, [1,3,6,1,3,7,1]).
-define(myName_instance, [1,3,6,1,3,7,1,0]).

-define(friendsTable, [1,3,6,1,3,7,4]).

-define(friendsEntry, [1,3,6,1,3,7,4,1]).
-define(fIndex, 1).
-define(fName, 2).
-define(fAddress, 3).
-define(fStatus, 4).


%% Range values
-define(low_myName, 0).
-define(high_myName, 255).
-define(low_fName, 0).
-define(high_fName, 255).
-define(low_fAddress, 0).
-define(high_fAddress, 255).


%% Enum definitions from fStatus
-define(fStatus_destroy, 6).
-define(fStatus_createAndWait, 5).
-define(fStatus_createAndGo, 4).
-define(fStatus_notReady, 3).
-define(fStatus_notInService, 2).
-define(fStatus_active, 1).

%% Default values
-define(default_myName, []).

-endif.
